### PR TITLE
modified run and setup batch files for tts pipeline

### PR DESCRIPTION
**Pull request by MKDYasserH**
Modified TTS pipeline steps in run.bat and setup.bat files to be similar to the other groups

### CODE REVIEW

**Review by wassfila — CHANGES_REQUESTED** [review]
looks good, I'll be testing it, just one point what is the ".idea" content ? Why not to .gitignore it ?
I prefer to keep the repo free from any ide specific code like vscode or any other.
we're also using gitsubmodules for the subrepos management I would also not mix with another system as it would confuse.

**Comment by wassfila** [comment]
- [ ] The production is still missing the matplotlib dependency

```
D:\Dev\SoundHacking\project_common>rg_production\venv\Scripts\python rg_production\main.py
[INFO   ] [Logger      ] Record log in C:\Users\User\.kivy\logs\kivy_21-08-11_0.txt
[INFO   ] [deps        ] Successfully imported "kivy_deps.angle" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.glew" 0.3.0
[INFO   ] [deps        ] Successfully imported "kivy_deps.sdl2" 0.3.1
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "D:\Dev\SoundHacking\project_common\rg_production\venv\lib\site-packages\kivy\__init__.py"
[INFO   ] [Python      ] v3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
[INFO   ] [Python      ] Interpreter at "D:\Dev\SoundHacking\project_common\rg_production\venv\Scripts\python.exe"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2 (img_pil, img_ffpyplayer ignored)
 Traceback (most recent call last):
   File "rg_production\main.py", line 13, in <module>
     from common.state.StateManager import StateManager, StateEnum
   File "D:\Dev\SoundHacking\project_common\rg_production\common\state\StateManager.py", line 5, in <module>
     from common.state.statecb import *
   File "D:\Dev\SoundHacking\project_common\rg_production\common\state\statecb.py", line 6, in <module>
     from common.taudio.PreprocessingSample import preprocess
   File "D:\Dev\SoundHacking\project_common\rg_production\common\taudio\PreprocessingSample.py", line 10, in <module>
     import matplotlib.pyplot as plt
 ModuleNotFoundError: No module named 'matplotlib'
```

**Review by wassfila — CHANGES_REQUESTED** [review]
sync both setup and setup3.8

**Comment by wassfila** [comment]
- [ ] regression in speech to text as it was running before missing `pyaudio`

```
D:\Dev\SoundHacking\project_common\rg_speech_to_text>venv\Scripts\python TheSoundOfAIOSR\stt\interface\server_app.py       
Traceback (most recent call last):
  File "TheSoundOfAIOSR\stt\interface\server_app.py", line 9, in <module>
    from TheSoundOfAIOSR.stt.interface.wsserver import SimpleServerInterface
  File "D:\Dev\SoundHacking\project_common\rg_speech_to_text\.\TheSoundOfAIOSR\stt\interface\wsserver.py", line 4, in <module>
    from TheSoundOfAIOSR.stt.control.stt_sm import SpeechToTextSM
  File "D:\Dev\SoundHacking\project_common\rg_speech_to_text\.\TheSoundOfAIOSR\stt\control\stt_sm.py", line 6, in <module>    
    from TheSoundOfAIOSR.stt.control.speech_to_text import SpeechToText
  File "D:\Dev\SoundHacking\project_common\rg_speech_to_text\.\TheSoundOfAIOSR\stt\control\speech_to_text.py", line 7, in <module>
    from TheSoundOfAIOSR.audiointerface.capture import MicrophoneCaptureFailed
  File "D:\Dev\SoundHacking\project_common\rg_speech_to_text\.\TheSoundOfAIOSR\audiointerface\capture.py", line 3, in <module>
    import pyaudio
ModuleNotFoundError: No module named 'pyaudio'
```

**Comment by wassfila** [comment]
- [ ] rg_text_to_sound not starting

```
D:\Dev\SoundHacking\project_common\rg_text_to_sound>venv/Scripts/python -m tts_websocketserver/src/tts_websocketserver/tts_server
'venv' is not recognized as an internal or external command,
operable program or batch file.
```
I updated the slashes but still another error, this does not seem to be tested with windows
```
D:\Dev\SoundHacking\project_common\rg_text_to_sound>venv\Scripts\python -m tts_websocketserver/src/tts_websocketserver/tts_server       
D:\Dev\SoundHacking\project_common\rg_text_to_sound\venv\Scripts\python.exe: No module named tts_websocketserver/src/tts_websocketserver/tts_server
```

**Comment by wassfila** [comment]
- [ ] check TODOs from #13

**Comment by wassfila** [comment]
@rubysubash , @MKDYasserH this PR is a good step forward yet it still require some stability improvements, it needs some effort indeed that maybe you could split across the Team.
Please make sure the following are applied to make sure everyone has the same environment :
 - [ ] test PR with a new freshly cloned `project_common` repo
 - [ ] follow steps identical to what is described in the readme, if any step is needed to be different then the readme can also be updated

**Comment by MKDYasserH** [comment]
> * [ ]  regression in speech to text as it was running before missing `pyaudio`
> 
> ```
> D:\Dev\SoundHacking\project_common\rg_speech_to_text>venv\Scripts\python TheSoundOfAIOSR\stt\interface\server_app.py       
> Traceback (most recent call last):
>   File "TheSoundOfAIOSR\stt\interface\server_app.py", line 9, in <module>
>     from TheSoundOfAIOSR.stt.interface.wsserver import SimpleServerInterface
>   File "D:\Dev\SoundHacking\project_common\rg_speech_to_text\.\TheSoundOfAIOSR\stt\interface\wsserver.py", line 4, in <module>
>     from TheSoundOfAIOSR.stt.control.stt_sm import SpeechToTextSM
>   File "D:\Dev\SoundHacking\project_common\rg_speech_to_text\.\TheSoundOfAIOSR\stt\control\stt_sm.py", line 6, in <module>    
>     from TheSoundOfAIOSR.stt.control.speech_to_text import SpeechToText
>   File "D:\Dev\SoundHacking\project_common\rg_speech_to_text\.\TheSoundOfAIOSR\stt\control\speech_to_text.py", line 7, in <module>
>     from TheSoundOfAIOSR.audiointerface.capture import MicrophoneCaptureFailed
>   File "D:\Dev\SoundHacking\project_common\rg_speech_to_text\.\TheSoundOfAIOSR\audiointerface\capture.py", line 3, in <module>
>     import pyaudio
> ModuleNotFoundError: No module named 'pyaudio'
> ```

I fixed this error by adding `pipwin refresh` to the setup and setup.3.8 batch files

**Comment by wassfila** [comment]
- [ ] windows anti-slash error

```
D:\Dev\SoundHacking\project_common>venv/Scripts/python -m tts_websocketserver/src/tts_websocketserver/tts_server
'venv' is not recognized as an internal or external command,
operable program or batch file.
```
image

**Review by wassfila — APPROVED** [review]

**Pull request merged**
