### PR TITLE
Ubuntu in WSL2 setup

### PR DESCRIPTION
**Pull request by tiborkiss**
_Prerequisites_: **WSL2 environment is configured**. Here I did not documented those few basic steps, since we can find in internet many descriptions. (Later we can add our shorter description.)

The scripts below is the same for WLS2 official version or from Insiders's build version.
Here we don't install any CUDA yet.

In a Windows PowerShell console, run the following
`.\ubuntu-setup\setup-wsl2.ps1`

It will pull down a fresh Ubuntu 20.04 LTS rootfs and it will register as `MusicAI` instance, create the default user called `ai` and it will configure pulseaudio client and update all the ubuntu packages.

Now we have a generic setup, with audio routed to host OS.

For running we don't need PowerShell, just a simple command line. I added `run_wsl2.bat` which starts a pulseaudio in host OS, which will be the server for internal audio in WSL2. Then it will start MusicAI instance.

After this diff should come the specific setups, which is completely common with native Ubuntu setup.
As a recommendation, one single WSL2 instance is enough for multiple research groups. Each service will be installed using a systemd script. Python environments can be separated for each group. That diffs come later a bit.

### CODE REVIEW

**Comment by tiborkiss** [comment]
If you would like to drop the instance, and recreate again..
`
wsl --unregister MusicAI
`

**Comment by wassfila** [comment]
@tiborkiss I prefer to keep the pulse audio in the "rg_speech_to_text" directory rather as it's a tool that is only relevant for the speech to text.

**Comment by wassfila** [comment]
ideally we should only have `setup_wsl2.bat` and `run_wsl2.bat` on the project common, nothing more and inside it we replace the calls to rg_speech_to_text by different ones calling setup and run scripts from within the rg_speech_to_text submodule.
This project_common is only inteded as glue between subprojects and I would avoid adding any code or dependencies into it.

**Comment by tiborkiss** [comment]
Pulseaudio cannot be part of the application, otherwise it would make the app to be wsl2 dependent. 
Pulseaudio is the required tool for any WSL2, in order to bind the audio to the soundcard. 
As any native Linux has the pulseaudio or alsa binding to the soundcard, for WSL2 pulseaudio could be one of them.
I understand, that for an app which does not need audio, it may not start the pulseaudio and leave WSL2 without the normal feature of any linux.

I thought that if is shared in a common place, if anyone needs linux, that would be a solution. But if there is no such interest. I will remove this pull request and I will mess within submodule or make another repo. Ideally, it should not be messed any application with wsl2, because it creates confusion for people who would like to use without wsl2, but native linux.

I will thinking what heathy options remains.

**Pull request closed without merging**
