### PR TITLE
new tts

### PR DESCRIPTION
**Pull request by Leofltt**
updated tts pipeline

### CODE REVIEW

**Review by wassfila — APPROVED** [review]

**Comment by am1tyadav** [comment]
I have an issue with this dev branch. The setup.bat does not finish successfully on Windows for me:

```
You can now load the package via spacy.load('en_core_web_lg')
INFO:absl:Using C:\Users\amity\AppData\Local\Temp\tfhub_modules to cache modules.
Traceback (most recent call last):
  File "C:\Users\amity\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\amity\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\soundofai\project_common\rg_text_to_sound\tts_websocketserver\src\tts_websocketserver\initialize.py", line 50, in <module>
    get_pipeline().build()
  File "F:\soundofai\project_common\rg_text_to_sound\tts_websocketserver\src\tts_websocketserver\..\..\..\tts_pipeline\src\tts_pipeline\pipelines\waterfall\pipeline.py", line 126, in build
    self.embedder.build()
  File "F:\soundofai\project_common\rg_text_to_sound\tts_websocketserver\src\tts_websocketserver\..\..\..\tts_pipeline\src\tts_pipeline\pipelines\waterfall\models\gnews_models.py", line 9, in build
    self.model = hub.load(self.tf_hub_url)
  File "F:\soundofai\project_common\rg_text_to_sound\venv\lib\site-packages\tensorflow_hub\module_v2.py", line 106, in load
    obj = tf.compat.v1.saved_model.load_v2(module_path, tags=tags)
  File "F:\soundofai\project_common\rg_text_to_sound\venv\lib\site-packages\tensorflow\python\saved_model\load.py", line 859, in load
    return load_internal(export_dir, tags, options)["root"]
  File "F:\soundofai\project_common\rg_text_to_sound\venv\lib\site-packages\tensorflow\python\saved_model\load.py", line 871, in load_internal
    loader_impl.parse_saved_model_with_debug_info(export_dir))
  File "F:\soundofai\project_common\rg_text_to_sound\venv\lib\site-packages\tensorflow\python\saved_model\loader_impl.py", line 56, in parse_saved_model_with_debug_info
    saved_model = _parse_saved_model(export_dir)
  File "F:\soundofai\project_common\rg_text_to_sound\venv\lib\site-packages\tensorflow\python\saved_model\loader_impl.py", line 111, in parse_saved_model
    raise IOError("SavedModel file does not exist at: %s/{%s|%s}" %
OSError: SavedModel file does not exist at: C:\Users\amity\AppData\Local\Temp\tfhub_modules\510580b203329a4a95dfdfefd838bdcd202f0d13/{saved_model.pbtxt|saved_model.pb}
```

This happens in the absolute last step when running `..\..\venv\Scripts\python -m tts_websocketserver.initialize`

Let me know if I missed something!

**Comment by Leofltt** [comment]
@am1tyadav can you check the location prompted in the last line and try deleting the contents of tfhub_models folder and then rerun the script?
I believe that's the issue, we need to put together an uninstaller for that

**Comment by Leofltt** [comment]
Please see issue #42 there might be additional Infos in there

**Comment by wassfila** [comment]
Right, I also think it's the same, at least similar,issue #42 and documented still in dev readme only
https://github.com/TheSoundOfAIOSR/project_common/tree/dev#setup-and-run

**Comment by am1tyadav** [comment]
You're right. Removing the temp folder inside tfhub_models and running `..\..\venv\Scripts\python -m tts_websocketserver.initialize` again did the job

**Comment by am1tyadav** [comment]
Also the sound generation module will need to be updated to latest - currently it quits because of a dependency

**Pull request merged**
