### PR TITLE
pulled latest soundgen and updated run + setup scripts

### PR DESCRIPTION
**Pull request by am1tyadav**
Pulled the latest commit from sound generation which removes the timbre_conditioned_vae dir
Updated the paths in run and setup scripts

### CODE REVIEW

**Comment by am1tyadav** [comment]
@Leofltt Could you validate when you get a chance? Works fine for me

**Review by Leofltt — APPROVED** [review]
Works for me too. Thanks @am1tyadav !

**Comment by Leofltt** [comment]
I don't have write access though, so we'll have to wait for someone else to merge

**Review by wassfila — APPROVED** [review]
thanks, looks good

**Pull request merged**
