### PR TITLE
Update setup / run scripts based on new sound generation

### PR DESCRIPTION
**Pull request by Leofltt**
Update setup / run scripts based on new sound generation

### CODE REVIEW

**Review by wassfila — APPROVED** [review]
I will update in the setup3.8 separately but we should maintain them in identical state, unfortunately I have to better option at the moment than to duplicate the content.

**Comment by wassfila** [comment]
@am1tyadav  I merged this PR, but I have a question, do you intentionally not want to use the latest commit from rg_sound_generation submodule ?

**Comment by wassfila** [comment]
no wrong comment I'll delete them

**Comment by am1tyadav** [comment]
@wassfila I don't think I created a PR, but I had left a message to Jesse to use my commit to test if everything works. I still have to add a few things for it to be fully ready for the main branch

**Pull request merged**
